Desktop version portfolio complete
sulaimanahmadi/Portfolio pull request #4
Opened 2023-06-07 10:14 UTC by sulaimanahmadi

**Add following things.**

- Use of flexbox and grid.
- Use media queries.
- Use Html and CSS.

2023-06-07 11:13 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @sulaimanahmadi , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media3.giphy.com/media/3o6wrebnKWmvx4ZBio/giphy.gif"/> |

## Highlights

- [ ].. ✅ Green linters
- [ ].. ✅ Clean code

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 11:13 UTC, joskalenda commented on desktop.css
> +.content-data > h2 {
- [ ] Your application is not responsive, @sulaimanahmadi, I think you should better use the `min-width` property and make sure you style your app accordingly as for now, it is not respecting any of your CSS in big screens

![6](https://github.com/sulaimanahmadi/Portfolio/assets/77843050/b193363a-9aee-4328-bace-d0136ca33218)

2023-06-07 11:51 UTC, sulaimanahmadi commented
Hello Dear ***@***.****
*I have changed some code and attached the video so kindly see to confirm
myself about it.*

Best regards

On Wed, Jun 7, 2023 at 3:43 PM Jos Kalenda ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: REQUIRED CHANGES ♻️
> Hi @sulaimanahmadi <https://github.com/sulaimanahmadi> ,
> Good job so far! There are some issues that you still need to work on to
> go to the next project but you are almost there!
>
> <https://camo.githubusercontent.com/2c34e7e812a3dac1247298f8cfde7dbdee5d167283940174f8ad2feee1139ce0/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f336f36777265626e4b576d7678345a42696f2f67697068792e676966>
> Highlights
>
>    - [ ].. ✅ Green linters
>    - [ ].. ✅ Clean code
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
> ------------------------------
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag ***@***.*** <https://github.com/joskalenda>)
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In desktop.css
> <https://github.com/sulaimanahmadi/Portfolio/pull/4#discussion_r1221401299>
> :
>
> > @@ -159,12 +159,31 @@ body {
>    flex-grow: 0;
>  }
>
> +.content-data > h2 {
>
>
>    - Your application is not responsive, @sulaimanahmadi
>    <https://github.com/sulaimanahmadi>, I think you should better use the
>    min-width property and make sure you style your app accordingly as for
>    now, it is not respecting any of your CSS in big screens
>
> [image: 6]
> <https://user-images.githubusercontent.com/77843050/244030408-b193363a-9aee-4328-bace-d0136ca33218.gif>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sulaimanahmadi/Portfolio/pull/4#pullrequestreview-1467371965>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4QVLCTINMQPBHFVHVRXCELXKBO5DANCNFSM6AAAAAAY5UMZGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-08 16:47 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @sulaimanahmadi 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 16:47 UTC, tresorsawasawa commented on style.css
>  .container {
- [ ] As mentioned by the previous reviewer and for the project requirements, kindly make sure your application is responsive and the design sticks as much as possible to the one from your chosen design. Below you can see hoew your application behaviors when changing the screen size.
![git](https://user-images.githubusercontent.com/77843050/244030408-b193363a-9aee-4328-bace-d0136ca33218.gif)

2023-06-09 00:51 UTC, sulaimanahmadi commented
Hello Dear  ***@***.****

*On behalf of my pull request, I requested the previous code reviewer also
to check my attached video therefore I made the desktop version portfolio
on a desktop screen and it is responsive so kindly watch my video.*

*best regards,*

On Thu, Jun 8, 2023 at 9:17 PM Tresor Sawasawa ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: REQUEST CHANGES ♻️♻️
>
> Hi @sulaimanahmadi <https://github.com/sulaimanahmadi>
> Great work on making the changes requested by the previous reviewer 👏👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
> [image: almost-there]
> <https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif>
> To highlight 🍾
>
>    - All linters are passing ✔️
>    - Good commit history ✔️
>    - Your design looks good 💯 ✔️
>    - Good PR description ✔️
>
> Required changes ♻️ ♻️
>
>    - Check the comments under the review.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
>
> *Feel free to leave any questions or comments in the PR thread if
> something is not 100% clear. Please ping me @tresorsawasawa
> <https://github.com/tresorsawasawa> when you comment so I can receive the
> notification or use slack with the same name.*
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/sulaimanahmadi/Portfolio/pull/4#discussion_r1223306174>
> :
>
> >    background-color: white;
>    margin: 0;
>    padding: 0;
> +  width: 100%;
>  }
>
>  .container {
>
>
>    - As mentioned by the previous reviewer and for the project
>    requirements, kindly make sure your application is responsive and the
>    design sticks as much as possible to the one from your chosen design. Below
>    you can see hoew your application behaviors when changing the screen size.
>    [image: git]
>    <https://user-images.githubusercontent.com/77843050/244030408-b193363a-9aee-4328-bace-d0136ca33218.gif>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sulaimanahmadi/Portfolio/pull/4#pullrequestreview-1470385893>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4QVLCTE22XEPCFZN772ZKDXKH62RANCNFSM6AAAAAAY5UMZGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-10 12:07 UTC, Cabraham1 approved these changes
Hi @sulaimanahmadi  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-12 03:51 UTC, merged